### ISSUE TITLE
[uWSGI ~ websocket] SystemError: you can call uwsgi api function only from the main callable

### ISSUE THREAD

**Issue by okayhooni** [pinterest/querybook#1319]
Related to: https://github.com/unbit/uwsgi/issues/980

After merging `master` branch to our custom branch today, I got the error like below, related to uWSGI, gevent and websocket.

How could I solve this issue..?

```
[pid: 28|app: 0|req: 132/130] 10.160.0.36 () {62 vars in 1401 bytes} [Fri Sep  1 11:35:50 2023] POST /ds/context_log/ => generated 42 bytes in 10 msecs (HTTP/1.1 200) 3 headers in 85 bytes (3 switches on core 998)
[BUG] current_wsgi_req NOT FOUND !!!
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.9/site-packages/engineio/socket.py", line 223, in writer
    ws.close()
  File "/usr/local/lib/python3.9/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 70, in close
    uwsgi.disconnect()
SystemError: you can call uwsgi api function only from the main callable
2023-09-01T11:35:50Z <Thread at 0x7f63a8909040: writer> failed with SystemError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 831, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 857, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/greenlet.py", line 846, in gevent._gevent_cgreenlet.Greenlet.join
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.9/site-packages/engineio/socket.py", line 223, in writer
    ws.close()
  File "/usr/local/lib/python3.9/site-packages/engineio/async_drivers/gevent_uwsgi.py", line 70, in close
    uwsgi.disconnect()
SystemError: you can call uwsgi api function only from the main callable
[pid: 28|app: 0|req: 133/131] 10.160.0.36 () {56 vars in 1260 bytes} [Fri Sep  1 11:35:48 2023] GET /-/socket.io/?EIO=4&transport=websocket => generated 2537 bytes in 1905 msecs (HTTP/1.1 101) 4 headers in 197 bytes (2 switches on core 995)
```

I use runservice script same as in the repo.
```
"prod_web")
    # gunicorn doesn't work with websocket
    # COMMAND="gunicorn -c querybook/server/gunicorn_conf.py app.server:flask_app"
    COMMAND="uwsgi --ini uwsgi.ini"
    ;;
```
```
[uwsgi]
http = :$(PORT)
gevent = 1000
wsgi-file = /opt/querybook/querybook/server/runweb.py
callable = flask_app
master = 1
http-websockets = 1
```

**Comment by okayhooni** [comment]
this issue was solved, thanks to the new release version (`v4.7.1`) of python-engineio.
