### ISSUE TITLE
docker image is missing requests_oauthlib library

### ISSUE THREAD

**Issue by brianmay** [pinterest/querybook#1350]
```
Running: python3 querybook/server/runweb.py --debug --webpack 10001
Traceback (most recent call last):
  File "/opt/querybook/querybook/server/runweb.py", line 18, in <module>
    from app.server import flask_app
  File "/opt/querybook/querybook/server/app/server.py", line 17, in <module>
    auth.init_app(flask_app)
  File "/opt/querybook/querybook/server/app/auth/__init__.py", line 15, in init_app
    load_auth()
  File "/opt/querybook/querybook/server/app/auth/__init__.py", line 37, in load_auth
    auth = import_module_with_default(QuerybookSettings.AUTH_BACKEND)
  File "/opt/querybook/querybook/server/lib/utils/import_helper.py", line 70, in import_module_with_default
    raise err
  File "/opt/querybook/querybook/server/lib/utils/import_helper.py", line 57, in import_module_with_default
    plugin_value = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/querybook/querybook/server/app/auth/oauth_auth.py", line 7, in <module>
    from requests_oauthlib import OAuth2Session
ModuleNotFoundError: No module named 'requests_oauthlib'
```

**Comment by brianmay** [comment]
Also the oauth scope appears to be hardcoded:
