### ISSUE TITLE
creating first doc error: Invalid meta type 

### ISSUE THREAD

**Issue by Ognian** [pinterest/querybook#508]
Hi,
I cloned today the repo and issues make. Beside the fact that I had to set `COMPOSE_HTTP_TIMEOUT=120; ` everything comes up. After registering the admin user I choose to setup everything by myself. I added an environment and a query engine (presto). After this I returned to the User UI and pressed the **+** for a new document, but I got:
```
Traceback (most recent call last): File "/opt/querybook/querybook/server/app/datasource.py", line 60, in handler results = fn(**kwargs) File "/opt/querybook/querybook/server/datasources/datadoc.py", line 99, in create_data_doc session=session, File "/opt/querybook/querybook/server/app/db.py", line 124, in func return fn(*args, **kwargs) File "/opt/querybook/querybook/server/logic/datadoc.py", line 62, in create_data_doc session=session, File "/opt/querybook/querybook/server/app/db.py", line 124, in func return fn(*args, **kwargs) File "/opt/querybook/querybook/server/logic/datadoc.py", line 296, in create_data_cell processed_meta = sanitize_data_cell_meta(cell_type, meta) File "/opt/querybook/querybook/server/logic/datadoc.py", line 285, in sanitize_data_cell_meta input_vals=meta, valid_vals=valid_dict, default_vals=default_dict File "/opt/querybook/querybook/server/logic/datadoc.py", line 251, in get_valid_meta default_vals.get(valid_key) if default_vals else None File "/opt/querybook/querybook/server/logic/datadoc.py", line 238, in get_valid_meta raise ValueError("Invalid meta type") ValueError: Invalid meta type
```

Any Idea?
Thanks
Ognian

**Comment by czgu** [comment]
Hi Ognian, sorry the instruction is not clear, but you would need to add the new query engine to the environment you have created.
Click add query engine here
![image](https://user-images.githubusercontent.com/8283407/114658822-538aaa00-9ca7-11eb-825e-cdbb50e435e5.png)

**Comment by Ognian** [comment]
@czgu  Thank's a lot, that was indeed not clear, but now it simply works...

**Comment by czgu** [comment]
@Ognian thanks for the feedback! I have added a PR to provide an easier to understand message
